version: "3.8"

services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true" # Disable ES bootstrap checks for containers
      SONAR_SEARCH_JAVAOPTS: "-Xms512m -Xmx512m" # Adjust heap size for ES
    depends_on:
      - db
    restart: always
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 2g # Limit container memory usage to 2GB
        reservations:
          memory: 1g # Reserve at least 1GB for this container

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1g # Limit container memory usage to 1GB
        reservations:
          memory: 512m # Reserve at least 512MB for this container
